#!/usr/bin/env bash

mkdir -p $HOME/bin

# Install hugo static site generator from GitHub releases page.
if [ -z "$HUGO_VERSION" ]; then
    echo "No hugo version set"
    exit 1
fi

echo "Installing Hugo v${HUGO_VERSION} to ~/bin"
curl -s -L "https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" | tar xzf - hugo
mv "./hugo" "$HOME/bin/hugo"
