name: Release
on:
  push:
    branches:
      - master
      - series/*
    tags: 
      - '*'
env:
  CI: true
  HUGO_VERSION: 0.26
  SCALA_VERSION: 2.12.10
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - uses: olafurpg/setup-gpg@v2    
      - name: Get current week
        run: |
          echo "::set-env name=current_week::$(( $(date +%U) ))"
          echo "::set-env name=last_week::$(( $(date +%U) - 1 ))"
      - name: Cache SBT coursier cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: coursier-${{ env.current_week }}
          restore-keys: coursier-${{ env.last_week }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ env.current_week }}
          restore-keys: sbt-${{ env.last_week }}
      - name: Publish
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}        
  publish-project-website:
    if: github.ref == 'refs/heads/master'
    name: Publish project site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - uses: olafurpg/setup-gpg@v2    
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: coursier-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
      - name: Add ~/bin to PATH
        run: echo "::add-path::$HOME/bin"
      - name: Install Hugo
        run: scripts/install-hugo
      - name: Publish
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "ghactions@invalid"
          sbt ++$SCALA_VERSION website/makeSite website/ghpagesPushSite
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  publish-docs:
    name: Publish docs site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - uses: olafurpg/setup-gpg@v2    
      - name: Get current week
        run: |
          echo "::set-env name=current_week::$(( $(date +%U) ))"
          echo "::set-env name=last_week::$(( $(date +%U) - 1 ))"
      - name: Cache SBT coursier cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: coursier-${{ env.current_week }}
          restore-keys: coursier-${{ env.last_week }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ env.current_week }}
          restore-keys: sbt-${{ env.last_week }}
      - name: Add ~/bin to PATH
        run: echo "::add-path::$HOME/bin"
      - name: Install Hugo
        run: scripts/install-hugo
      - name: Publish
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "ghactions@invalid"
          sbt ++$SCALA_VERSION docs/makeSite docs/ghpagesPushSite
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
